---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: audit.stringApprove

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: number-property
          operator: eq
          operands:
            - 2
    flagValue: stringVal
