---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: audit.stringReject

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.distinct_id
          operator: is-undefined
    flagValue: fsfa
