---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: audit.numApprove

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: number-property
          operator: lt
          operands:
            - 6756
    flagValue: 3423
