---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: NandhaTest number

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: 48

conditions:
  - allOf:
      - anyOf:
          - group:
              name: NandhaTest
    flagValue: 123
