---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: NandhaTest str

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: nandha

conditions:
  - allOf:
      - property:
          name: number-property
          operator: ne
          operands:
            - 100
    flagValue: nandha
