---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Campaign1Flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - flag:
          name: jesus.stringFlag
          value: aSD
    flagValue: hello
