---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: flagForRomain

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 0
    from: 2025-07-24T13:56:00Z
  - percentage: 100
    from: 2025-07-24T14:01:00Z

conditions:
  - allOf:
      - property:
          name: prop1
          operator: is-true
    flagValue: true
