---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: flag-for-test-reject-approval

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: test1

conditions:
  - allOf:
      - property:
          name: stringProp
          operator: in-array
          operands:
            - test
    flagValue: test123
  - allOf:
      - anyOf:
          - group:
              name: TG1
    flagValue: test0
