---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: jesus.stringFlag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: numProp
          operator: lt
          operands:
            - 6
    flagValue:
      valueWrittenInCode: true
  - allOf:
      - flag:
          name: GregBoolFlag
          value: "true"
    flagValue: aSD
