---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: audit.BoolFlagTest

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: regex
          operands:
            - sdfwr
    flagValue: false
